# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: "<%=ENV['domain_name']%>"
  mark: "<%=ENV['mark']%>"
  rooter: "<%=ENV['rooter']%>"
  redis_pw:  "<%=ENV['redis_pw']%>"
  secret_key_base:  "<%=ENV['secret_key_base']%>"
  #mailgun_api_key:  "<%=ENV['mailgun_api_key']%>" 
  #mailgun_domain:  "<%=ENV['mailgun_domain']%>"
  #mail_from: <%=ENV['from']%>
  mail_from: = "<%=ENV['mail_from']%>"
  #sparkpost_api_key: "<%=ENV['sparkpost_api_key']%>" 
test:
  domain_name: "<%=ENV['domain_name']%>"
  mark: "<%=ENV['mark']%>"
  rooter: "<%=ENV['rooter']%>"
  redis_pw:  "<%=ENV['redis_pw']%>"
  secret_key_base:  "<%=ENV['secret_key_base']%>"
  #mailgun_api_key:  "<%=ENV['mailgun_api_key']%>" 
  #mailgun_domain:  "<%=ENV['mailgun_domain']%>"
  mail_from: "<%=ENV['mail_from']%>"
  #sparkpost_api_key = <%=ENV['sparkpost_api_key']%>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  rooter: "<%=ENV['rooter']%>"
  mark: "<%=ENV['mark']%>"  
  domain_name: "<%= ENV['domain_name']%>"
  redis_pw:  "<%=ENV['redis_pw']%>"
  secret_key_base:  "<%=ENV['secret_key_base']%>"
  #mailgun_api_key:  "<%=ENV['mailgun_api_key']%>" 
  #mailgun_domain:  "<%=ENV['mailgun_domain']%>" 
  #mail_from: "<%=ENV['from']%>"
  mail_from: "<%=ENV['mail_from']%>"
  sparkpost_api_key: "<%=ENV['sparkpost_api_key']%>"
 # used for testing production
  #redis_local_pw: ENV['redis_local_pw]
