puts opx.equal
 puts opx.equals
 puts opx.not_equal
 puts opx.equal_case_insenstive
  puts opx.not_equal_case_insensitive
 puts opx.less_than_or_equal_to_date
 puts opx.greater_than_or_equal_to_date
 puts opx.less_than
 puts opx.greater_than
 puts opx.contains
 puts opx.does_not_contain
 puts opx.matches
 puts opx.does_not_match
  puts opx.starts_with
 puts opx.like
 puts opx.not_like
 puts opx.is_like
  puts opx.is_not_like
 puts opx.starts_with
 puts opx.begins_with
 puts opx.empty_str
 puts opx.ends_with
  puts opx.empty_str
 puts opx.is_empty_str
 puts opx.blank_str
 puts opx.is_blank_str
  puts opx.is_null
 puts opx.is_nil
 puts opx.is_empty
 puts opx.not_null
 puts opx.is_not_null
  puts opx.in
 puts opx.not_in
 puts opx.is_not_in
 puts opx.is_in
 puts opx.contained_in
 puts opx.is_contained_in
  puts opx.not_contained_in
 puts opx.is_equal_to
 puts opx.equal_to
 puts opx.not_equal_to
 puts opx.is_not_equal_to