require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpecialPartialDotKeysController do

  # This should return the minimal set of attributes required to create a valid
  # SpecialPartialDotKey. As you add validations to SpecialPartialDotKey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "partial_dot_key" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpecialPartialDotKeysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all special_partial_dot_keys as @special_partial_dot_keys" do
      special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
      get :index, {}, valid_session
      assigns(:special_partial_dot_keys).should eq([special_partial_dot_key])
    end
  end

  describe "GET show" do
    it "assigns the requested special_partial_dot_key as @special_partial_dot_key" do
      special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
      get :show, {:id => special_partial_dot_key.to_param}, valid_session
      assigns(:special_partial_dot_key).should eq(special_partial_dot_key)
    end
  end

  describe "GET new" do
    it "assigns a new special_partial_dot_key as @special_partial_dot_key" do
      get :new, {}, valid_session
      assigns(:special_partial_dot_key).should be_a_new(SpecialPartialDotKey)
    end
  end

  describe "GET edit" do
    it "assigns the requested special_partial_dot_key as @special_partial_dot_key" do
      special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
      get :edit, {:id => special_partial_dot_key.to_param}, valid_session
      assigns(:special_partial_dot_key).should eq(special_partial_dot_key)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpecialPartialDotKey" do
        expect {
          post :create, {:special_partial_dot_key => valid_attributes}, valid_session
        }.to change(SpecialPartialDotKey, :count).by(1)
      end

      it "assigns a newly created special_partial_dot_key as @special_partial_dot_key" do
        post :create, {:special_partial_dot_key => valid_attributes}, valid_session
        assigns(:special_partial_dot_key).should be_a(SpecialPartialDotKey)
        assigns(:special_partial_dot_key).should be_persisted
      end

      it "redirects to the created special_partial_dot_key" do
        post :create, {:special_partial_dot_key => valid_attributes}, valid_session
        response.should redirect_to(SpecialPartialDotKey.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved special_partial_dot_key as @special_partial_dot_key" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialPartialDotKey.any_instance.stub(:save).and_return(false)
        post :create, {:special_partial_dot_key => { "partial_dot_key" => "invalid value" }}, valid_session
        assigns(:special_partial_dot_key).should be_a_new(SpecialPartialDotKey)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialPartialDotKey.any_instance.stub(:save).and_return(false)
        post :create, {:special_partial_dot_key => { "partial_dot_key" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested special_partial_dot_key" do
        special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
        # Assuming there are no other special_partial_dot_keys in the database, this
        # specifies that the SpecialPartialDotKey created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpecialPartialDotKey.any_instance.should_receive(:update).with({ "partial_dot_key" => "MyString" })
        put :update, {:id => special_partial_dot_key.to_param, :special_partial_dot_key => { "partial_dot_key" => "MyString" }}, valid_session
      end

      it "assigns the requested special_partial_dot_key as @special_partial_dot_key" do
        special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
        put :update, {:id => special_partial_dot_key.to_param, :special_partial_dot_key => valid_attributes}, valid_session
        assigns(:special_partial_dot_key).should eq(special_partial_dot_key)
      end

      it "redirects to the special_partial_dot_key" do
        special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
        put :update, {:id => special_partial_dot_key.to_param, :special_partial_dot_key => valid_attributes}, valid_session
        response.should redirect_to(special_partial_dot_key)
      end
    end

    describe "with invalid params" do
      it "assigns the special_partial_dot_key as @special_partial_dot_key" do
        special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialPartialDotKey.any_instance.stub(:save).and_return(false)
        put :update, {:id => special_partial_dot_key.to_param, :special_partial_dot_key => { "partial_dot_key" => "invalid value" }}, valid_session
        assigns(:special_partial_dot_key).should eq(special_partial_dot_key)
      end

      it "re-renders the 'edit' template" do
        special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialPartialDotKey.any_instance.stub(:save).and_return(false)
        put :update, {:id => special_partial_dot_key.to_param, :special_partial_dot_key => { "partial_dot_key" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested special_partial_dot_key" do
      special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
      expect {
        delete :destroy, {:id => special_partial_dot_key.to_param}, valid_session
      }.to change(SpecialPartialDotKey, :count).by(-1)
    end

    it "redirects to the special_partial_dot_keys list" do
      special_partial_dot_key = SpecialPartialDotKey.create! valid_attributes
      delete :destroy, {:id => special_partial_dot_key.to_param}, valid_session
      response.should redirect_to(special_partial_dot_keys_url)
    end
  end

end
